spring:
  profiles: pro
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.78.152:3306/teacher_performance_pro?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: tpas_admin
    password: AaBb2020!
    initialSize: 10
    maxWait: 250
    keepAlive: true
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    minIdle: 8
    maxActive: 10

#mybatisPlus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.management.tpas.entity,com.business.tpas.entity

# 服务器端口
server:
  port: 8080

