spring:
  profiles: dev
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.78.152:3306/teacher_performance_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: tpas_admin
    password: AaBb2020!
    druid:
      initialSize: 10
      maxWait: 250
      keepAlive: true
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      minIdle: 8
      maxActive: 10
  redis:
    database: 2 # 数据库索引(默认为 0)
    host: localhost
    port: 6379
    password: AaBb2020! # 服务器链接密码
    lettuce:
      pool:
        max-active: 8 # 最大连接数(负值表示没有限制)
        max-wait: -1 # 最大阻塞等待时间(负值表示没有限制)
        max-idle: 8 # 最大空闲连接
        min-idle: 0 # 最小空闲连接
    timeout: 5000 # 连接超时时间(毫秒)

#mybatisPlus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.management.tpas.entity,com.business.tpas.entity

# 服务器端口
server:
  port: 8082

# jwt令牌配置
jwt:
  jwt-secret: 6tzgvki3FUAQmVat0xhFSggFOTSsVHEb # 秘钥
  expire-time: 1 # 有效小时数

logging:
  level:
    com.management.tpas.dao: debug

# 配置swagger开关，关闭生产环境swagger
swagger:
  enable: true